export {default as Header} from "./header"
export {default as Footer} from "./footer"
export {default as Card} from "./card"
export {default as Heading} from "./heading"
export {default as Page} from "./page"